apiVersion: v1
kind: Service
metadata:
  name: payments-api
spec:
  selector:
    app: payments-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
      nodePort: 30004